name: CI Pipe

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'implementations/**'
      - '.github/workflows/**'
  push:
    branches: [ "master" ]
    paths:
      - 'implementations/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint implementations --rcfile=.github/pylint.conf --disable=E0401 --disable=C0103 --disable=R1728